// Headerdatei für CLStep4

#ifndef __CLStep4__
#define __CLStep4__


/////////////////////////////////////////////////////////////////////////////////////////////
// C-Kapselung für LStep4.DLL

const int XAxis = 1;
const int YAxis = 2;
const int ZAxis = 3;
const int AAxis = 4;


#ifdef __cplusplus
    extern "C" {
#endif


/*#pragma pack(1)
struct TLS_ControlInitPar
{
      int Size;
      int InterfaceType;
      char ComNameLength;
      char ComName[32];
      BOOL ShowProt;
      BOOL ShowCmdList;

      int BaudRate;
      int IOAdress;
      int CardIndex;

      int ControlType;
      char VersionStrLength;
      char VersionStr[64];
      int Axes;
      int ErrorCode;
      BOOL NewCmds;
      int Encoder;
      BOOL Display, SpeedPoti, HandWheel, Snapshot, TVR, TriggerOut;
      BOOL DemoMode;
};
#pragma pack(8)
 */

typedef int (__stdcall *PConnect) (void);
typedef int (__stdcall *PConnectSimple) (int lAnInterfaceType, char *pcAComName, int lABaudRate, BOOL bAShowProt);
//typedef int (__stdcall *PConnectEx) (TLS_ControlInitPar *pAControlInitPar);
typedef int (__stdcall *PDisconnect) (void);
typedef int (__stdcall *PLoadConfig) (char *pcFileName);
typedef int (__stdcall *PSaveConfig) (char *pcFileName);
typedef int (__stdcall *PMoveAbs) (double dX, double dY, double dZ, double dA, BOOL bWait);
typedef int (__stdcall *PMoveRel) (double dX, double dY, double dZ, double dA, BOOL bWait);
typedef int (__stdcall *PCalibrate) (void);
typedef int (__stdcall *PRMeasure) (void);
typedef int (__stdcall *PSetPitch) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetPos) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetActiveAxes) (int lFlags);
typedef int (__stdcall *PSetVel) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetAccel) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetReduction) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetDelay) (int lDelay);
typedef int (__stdcall *PSetSwitchPolarity) (int lXP, int lYP, int lZP, int lAP);
typedef int (__stdcall *PSetSwitchActive) (int lXA, int lYA, int lZA, int lAA);
typedef int (__stdcall *PSetJoystickOn) (BOOL bPositionCount, BOOL bEncoder);
typedef int (__stdcall *PSetJoystickOff) (void);
typedef int (__stdcall *PSoftwareReset) (void);
typedef int (__stdcall *PSetDigitalOutput) (int lIndex, BOOL bValue);
typedef int (__stdcall *PGetDigitalInputs) (int *plValue);
typedef int (__stdcall *PSetAnalogOutput) (int lIndex, int lValue);
typedef int (__stdcall *PGetAnalogInput) (int lIndex, int *plValue);
typedef int (__stdcall *PSetLimit) (int lAxis, double dMinRange, double dMaxRange);
typedef int (__stdcall *PSetLimitControl) (int lAxis, BOOL bActive);
typedef int (__stdcall *PGetPos) (double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetStatus) (char *pcStat, int lMaxLen);
typedef int (__stdcall *PGetEncoderMask) (int *plFlags);
typedef int (__stdcall *PStopAxes) (void);
typedef int (__stdcall *PSetAbortFlag) (void);
typedef int (__stdcall *PMoveRelSingleAxis) (int lAxis, double dValue, BOOL bWait);
typedef int (__stdcall *PMoveAbsSingleAxis) (int lAxis, double dValue, BOOL bWait);
typedef int (__stdcall *PSetControlPars) (void);
typedef int (__stdcall *PSetMotorCurrent) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetVelSingleAxis) (int lAxis, double dVel);
typedef int (__stdcall *PSetAccelSingleAxis) (int lAxis, double dAccel);
typedef int (__stdcall *PCalibrateEx) (int lFlags);
typedef int (__stdcall *PRMeasureEx) (int lFlags);
typedef int (__stdcall *PSetShowProt) (BOOL bShowProt);
typedef int (__stdcall *PGetAnalogInputs2) (int *plPT100, int *plMV, int *plV24);
typedef int (__stdcall *PSendString) (char *pcStr, char *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
typedef int (__stdcall *PSetSpeedPoti) (BOOL bSpeedPoti);
typedef int (__stdcall *PSetTVRMode) (int lXT, int lYT, int lZT, int lAT);
typedef int (__stdcall *PSetAutoStatus) (int lValue);
typedef int (__stdcall *PGetStatusAxis) (char *pcStatusAxisStr, int lMaxLen);
typedef int (__stdcall *PSetDigIO_Off) (int lIndex);
typedef int (__stdcall *PSetDigIO_Polarity) (int lIndex, BOOL bHigh);
typedef int (__stdcall *PSetDigIO_EmergencyStop) (int lIndex);
typedef int (__stdcall *PSetDigIO_Distance) (int lIndex, BOOL bFkt, double dDist, int lAxis);
typedef int (__stdcall *PSetDimensions) (int lXD, int lYD, int lZD, int lAD);
typedef int (__stdcall *PMoveRelShort) (void);
typedef int (__stdcall *PSetEncoderPeriod) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetJoystickDir) (int lXD, int lYD, int lZD, int lAD);
typedef int (__stdcall *PSetEncoderMask) (int lValue);
typedef int (__stdcall *PSetGear) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetHandWheelOn) (BOOL bPositionCount, BOOL bEncoder);
typedef int (__stdcall *PSetHandWheelOff) (void);
typedef int (__stdcall *PSetFactorTVR) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetTargetWindow) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetController) (int lXC, int lYC, int lZC, int lAC);
typedef int (__stdcall *PSetControllerCall) (int lCtrCall);
typedef int (__stdcall *PSetControllerSteps) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetControllerFactor) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetControllerTWDelay) (int lCtrTWDelay);
typedef int (__stdcall *PSetEncoderRefSignal) (int lXR, int lYR, int lZR, int lAR);
typedef int (__stdcall *PSetEncoderPosition) (BOOL bValue);
typedef int (__stdcall *PGetVersionStr) (char *pcVers, int lMaxLen);
typedef int (__stdcall *PGetError) (int *plErrorCode);
typedef int (__stdcall *PGetPosSingleAxis) (int lAxis, double *pdPos);
typedef int (__stdcall *PSetDistance) (double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PGetPosEx) (double *pdX, double *pdY, double *pdZ, double *pdR, BOOL bEncoder);
typedef int (__stdcall *PSetShowCmdList) (BOOL bShowCmdList);
typedef int (__stdcall *PSetWriteLogText) (BOOL bAWriteLogText);
typedef int (__stdcall *PSetControllerTimeout) (int lACtrTimeout);
typedef int (__stdcall *PSetEncoderActive) (int lFlags);
typedef int (__stdcall *PGetSnapshotCount) (int *plSnsCount);
typedef int (__stdcall *PGetSnapshotPos) (double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PSetCorrTblOff) (void);
typedef int (__stdcall *PSetCorrTblOn) (char *pcAFileName);
typedef int (__stdcall *PSetFactorMode) (BOOL bAFactorMode, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetSnapshot) (BOOL bASnapshot);
typedef int (__stdcall *PSetSnapshotPar) (BOOL bHigh, BOOL bAutoMode);
typedef int (__stdcall *PSetTrigger) (BOOL bATrigger);
typedef int (__stdcall *PSetTriggerPar) (int lAxis, int lMode, int lSignal, double dDistance);
typedef int (__stdcall *PSetLanguage) (char *pcPLN);
typedef int (__stdcall *PGetSwitches) (int *plFlags);
typedef int (__stdcall *PGetSerialNr) (char *pcSerialNr, int lMaxLen);
typedef int (__stdcall *PSetCalibOffset) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PSetRMOffset) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetSnapshotPosArray) (int lIndex, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetAxisDirection) (int lXD, int lYD, int lZD, int lAD);
typedef int (__stdcall *PSetCalibrateDir) (int lXD, int lYD, int lZD, int lAD);
typedef int (__stdcall *PLStepSave) (void);
typedef int (__stdcall *PSetBPZ) (int lAValue);
typedef int (__stdcall *PSetBPZTrackballFactor) (double dAValue);
typedef int (__stdcall *PSetBPZTrackballBackLash) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PSetBPZJoyspeed) (int lAPar, double dAValue);
typedef int (__stdcall *PSetJoystickWindow) (int lAValue);
typedef int (__stdcall *PSetCurrentDelay) (int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PMoveEx) (double dX, double dY, double dZ, double dR, BOOL bRelative, BOOL bWait, int lAxisCount);
typedef int (__stdcall *PWaitForAxisStop) (int lAFlags, int lATimeoutValue, BOOL *pbATimeout);
typedef int (__stdcall *PSetProcessMessagesProc) (void* pProc);
typedef int (__stdcall *PSendStringPosCmd) (char *pcStr, char *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
typedef int (__stdcall *PSetDigitalOutputs) (int lValue);
typedef int (__stdcall *PSetWriteLogTextFN) (BOOL bAWriteLogText, char *pcALogFN);
typedef int (__stdcall *PSetDigitalOutputsE) (int lValue);
typedef int (__stdcall *PGetDigitalInputsE) (int *plValue);
typedef int (__stdcall *PEnableCommandRetry) (BOOL bAValue);
typedef int (__stdcall *PSetXYAxisComp) (int lValue);
typedef int (__stdcall *PGetVersionStrDet) (char *pcVersDet, int lMaxLen);
typedef int (__stdcall *PGetAPIVersion) (char *pcAPIVer, int lMaxLen);
typedef int (__stdcall *PSetCommandTimeout) (int lAtoRead, int lAtoMove, int lAtoCalibrate);
typedef int (__stdcall *PSetExtValue) (int lAName, int lAValue);
typedef int (__stdcall *PFlushBuffer) (int lAValue);
typedef int (__stdcall *PGetEEPRomValue) (short Offset, short *pValue);
typedef int (__stdcall *PSetEEPRomValue) (short Offset, short Value);
typedef int (__stdcall *PGetXYAxisComp) (int *plValue);
typedef int (__stdcall *PGetDimensions) (int *plXD, int *plYD, int *plZD, int *plAD);
typedef int (__stdcall *PGetPitch) (double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetGear) (double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetVel) (double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetAccel) (double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PSetVelFac) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PSetVelFacSingleAxis) (int lAxis, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetVelFac) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetSpeedPoti) (BOOL *pbSpePoti);
typedef int (__stdcall *PGetMotorCurrent) (double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetReduction) (double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetCurrentDelay) (int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetOutFuncLev) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetOutFuncLev) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetActiveAxes) (int *plFlags);
typedef int (__stdcall *PGetAxisDirection) (int *plXD, int *plYD, int *plZD, int *plAD);
typedef int (__stdcall *PGetCalibOffset) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetRMOffset) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetCalibrateDir) (int *plXD, int *plYD, int *plZD, int *plAD);
typedef int (__stdcall *PSetCalibBackSpeed) (int lSpeed);
typedef int (__stdcall *PGetCalibBackSpeed) (int *plSpeed);
typedef int (__stdcall *PSetRefSpeed) (int lSpeed);
typedef int (__stdcall *PGetRefSpeed) (int *plSpeed);
typedef int (__stdcall *PSetPowerAmplifier) (BOOL bAmplifier);
typedef int (__stdcall *PGetPowerAmplifier) (BOOL *pbAmplifier);
typedef int (__stdcall *PSetMotorTablePatch) (BOOL bActive);
typedef int (__stdcall *PGetMotorTablePatch) (BOOL *pbActive);
typedef int (__stdcall *PSetJoystickFilter) (BOOL bActive);
typedef int (__stdcall *PGetJoystickFilter) (BOOL *pbActive);
typedef int (__stdcall *PSetStopPolarity) (BOOL bHighActiv);
typedef int (__stdcall *PGetStopPolarity) (BOOL *pbHighActiv);
typedef int (__stdcall *PSetVLevel) (int lVRegion, double dDownLevel, double dUppLevel);
typedef int (__stdcall *PGetVLevel) (int lVRegion, double *pdDownLevel, double *pdUppLevel);
typedef int (__stdcall *PSetStopAccel) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetStopAccel) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PGetVersionStrInfo) (char *pcVersInfo, int lMaxLen);
typedef int (__stdcall *PGetStatusLimit) (char *pcLimit, int lMaxLen);
typedef int (__stdcall *PGetSecurityErr) (DWORD *pdwValue);
typedef int (__stdcall *PGetSecurityStatus) (DWORD *pdwValue);
typedef int (__stdcall *PGetDelay) (int *plDelay);
typedef int (__stdcall *PGetDistance) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PClearPos) (int lFlags);
typedef int (__stdcall *PSetDigJoySpeed) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetDigJoySpeed) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetJoystickDir) (int *plXD, int *plYD, int *plZD, int *plRD);
typedef int (__stdcall *PGetJoystick) (BOOL *pbJoystickOn, BOOL *pbManual, BOOL *pbPositionCount, BOOL *pbEncoder);
typedef int (__stdcall *PGetJoystickWindow) (int *plAValue);
typedef int (__stdcall *PGetHandWheel) (BOOL *pbHandWheelOn, BOOL *pbPositionCount, BOOL *pbEncoder);
typedef int (__stdcall *PGetBPZ) (int *plAValue);
typedef int (__stdcall *PGetBPZTrackballFactor) (double *pdAValue);
typedef int (__stdcall *PGetBPZTrackballBackLash) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetBPZJoyspeed) (int lAPar, double *pdAValue);
typedef int (__stdcall *PGetLimitControl) (int lAxis, BOOL *pbActive);
typedef int (__stdcall *PSetAutoLimitAfterCalibRM) (int lFlags);
typedef int (__stdcall *PGetAutoLimitAfterCalibRM) (int *plFlags);
typedef int (__stdcall *PGetSwitchPolarity) (int *plXP, int *plYP, int *plZP, int *plRP);
typedef int (__stdcall *PGetSwitchActive) (int *plXA, int *plYA, int *plZA, int *plRA);
typedef int (__stdcall *PGetTVRMode) (int *plXT, int *plYT, int *plZT, int *plRT);
typedef int (__stdcall *PGetFactorTVR) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetTVROutMode) (int lXT, int lYT, int lZT, int lRT);
typedef int (__stdcall *PGetTVROutMode) (int *plXT, int *plYT, int *plZT, int *plRT);
typedef int (__stdcall *PSetTVROutResolution) (int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PGetTVROutResolution) (int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetTVROutPitch) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetTVROutPitch) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetVelTVRO) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetVelTVRO) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetAccelTVRO) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetAccelTVRO) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetVelSingleAxisTVRO) (int lAxis, double dVel);
typedef int (__stdcall *PSetAccelSingleAxisTVRO) (int lAxis, double dAccel);
typedef int (__stdcall *PSetPosTVRO) (double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetPosTVRO) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PMoveAbsTVRO) (double dX, double dY, double dZ, double dR, BOOL bWait);
typedef int (__stdcall *PMoveRelTVRO) (double dX, double dY, double dZ, double dR, BOOL bWait);
typedef int (__stdcall *PMoveRelTVROSingleAxis) (int lAxis, double dValue, BOOL bWait);
typedef int (__stdcall *PMoveAbsTVROSingleAxis) (int lAxis, double dValue, BOOL bWait);
typedef int (__stdcall *PGetStatusTVRO) (char *pcStat, int lMaxLen);
typedef int (__stdcall *PGetTargetWindow) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetEncoderPeriod) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetEncoderRefSignal) (int *plXR, int *plYR, int *plZR, int *plRR);
typedef int (__stdcall *PGetEncoderPosition) (BOOL *pbValue);
typedef int (__stdcall *PGetEncoderActive) (int *plFlags);
typedef int (__stdcall *PGetController) (int *plXC, int *plYC, int *plZC, int *plRC);
typedef int (__stdcall *PGetControllerCall) (int *plCtrCall);
typedef int (__stdcall *PGetControllerSteps) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetControllerFactor) (double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetControllerTWDelay) (int *plCtrTWDelay);
typedef int (__stdcall *PGetControllerTimeout) (int *plACtrTimeout);
typedef int (__stdcall *PSetCtrFastMoveOn) (void);
typedef int (__stdcall *PSetCtrFastMoveOff) (void);
typedef int (__stdcall *PGetCtrFastMove) (BOOL *pbActive);
typedef int (__stdcall *PClearCtrFastMoveCounter) (void);
typedef int (__stdcall *PGetCtrFastMoveCounter) (int *plXC, int *plYC, int *plZC, int *plRC);
typedef int (__stdcall *PClearEncoder) (int lAxis);
typedef int (__stdcall *PGetEncoder) (double *pdXP, double *pdYP, double *pdZP, double *pdRP);
typedef int (__stdcall *PGetTrigger) (BOOL *pbATrigger);
typedef int (__stdcall *PGetTriggerPar) (int *plAxis, int *plMode, int *plSignal, double *pdDistance);
typedef int (__stdcall *PSetTrigCount) (int lValue);
typedef int (__stdcall *PGetTrigCount) (int *plValue);
typedef int (__stdcall *PSetTVRInPulse) (int lAxis, BOOL bDirection);
typedef int (__stdcall *PGetSnapshot) (BOOL *pbASnapshot);
typedef int (__stdcall *PSetSnapshotFilter) (int lTime);
typedef int (__stdcall *PGetSnapshotFilter) (int *plTime);
typedef int (__stdcall *PGetSnapshotPar) (BOOL *pbHigh, BOOL *pbAutoMode);
typedef int (__stdcall *PGetLimit) (int lAxis, double *pdMinRange, double *pdMaxRange);
typedef int (__stdcall *PJoyChangeAxis) (BOOL bValue);
typedef int (__stdcall *PGetJoyChangeAxis) (BOOL *pbValue);
typedef int (__stdcall *PSetDigJoyOff) (void);
typedef int (__stdcall *PSetInputTrigMove) (int lMode, BOOL bWait);
typedef int (__stdcall *PGetInputTrigMove) (int *plMode);
typedef int (__stdcall *PSetLimitControlMode) (int lMode);
typedef int (__stdcall *PGetLimitControlMode) (int *plMode);
typedef int (__stdcall *PInitialize) (char *pcWorkpath);
typedef int (__stdcall *PSetAccelJerk) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PSetDecelJerk) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PSetCalibRMJerk) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PSetJoyVel) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetJoyVel) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetDeceleration) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetDeceleration) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetDecelSingleAxis) (int lAxis, double dValue);
typedef int (__stdcall *PConfigMaxAxes) (int lnAxes);
typedef int (__stdcall *PSetJoystickAxes) (int lFlags);
typedef int (__stdcall *PGetJoystickAxes) (int *plFlags);
typedef int (__stdcall *PSetJoyVelSkal) (int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PGetJoyVelSkal) (int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetMaxUserCurrent) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetMaxUserCurrent) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetStopDecel) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetStopDecel) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetMotorMaxVel) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetMotorMaxVel) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetMotorStandForce) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetMotorStandForce) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetMotorStandMoment) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetMotorStandMoment) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetMotorFieldDir) (int lX, int lY, int lZ, int lA);
typedef int (__stdcall *PGetMotorFieldDir) (int *plX, int *plY, int *plZ, int *plA);
typedef int (__stdcall *PSetMotorType) (int lX, int lY, int lZ, int lA);
typedef int (__stdcall *PGetMotorType) (int *plX, int *plY, int *plZ, int *plA);
typedef int (__stdcall *PSetOsziCallBackFct) (void* pFct);
typedef int (__stdcall *PSetCalibRMAccel) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetCalibRMAccel) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PGetCalibRMJerk) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetCalibRMVel) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetCalibRMVel) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetCalibRMBackSpeed) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetCalibRMBackSpeed) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PGetAccelJerk) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PGetDecelJerk) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetGearDenominator) (int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PGetGearDenominator) (int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetGearNumerator) (int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PGetGearNumerator) (int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetStopDecelJerk) (double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetStopDecelJerk) (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetSwChange) (int lFlags);
typedef int (__stdcall *PGetSwChange) (int *plFlags);



//	    int		GetDLLLoadResult(void) {return m_DLLResultat;}; // Funktion, ob Laden der DLL erfolgreich war.
	// sollte Wert 0 zurückgeben

	// Funktionen der Dll
        int Connect (void);
        int ConnectSimple (int lAnInterfaceType, char *pcAComName, int lABaudRate, BOOL bAShowProt);
      //  int ConnectEx (TLS_ControlInitPar *pAControlInitPar);
        int Disconnect (void);
        int LoadConfig (char *pcFileName);
        int SaveConfig (char *pcFileName);
        int MoveAbs (double dX, double dY, double dZ, double dA, BOOL bWait);
        int MoveRel (double dX, double dY, double dZ, double dA, BOOL bWait);
        int Calibrate (void);
        int RMeasure (void);
        int SetPitch (double dX, double dY, double dZ, double dA);
        int SetPos (double dX, double dY, double dZ, double dA);
        int SetActiveAxes (int lFlags);
        int SetVel (double dX, double dY, double dZ, double dA);
        int SetAccel (double dX, double dY, double dZ, double dA);
        int SetReduction (double dX, double dY, double dZ, double dA);
        int SetDelay (int lDelay);
        int SetSwitchPolarity (int lXP, int lYP, int lZP, int lAP);
        int SetSwitchActive (int lXA, int lYA, int lZA, int lAA);
        int SetJoystickOn (BOOL bPositionCount, BOOL bEncoder);
        int SetJoystickOff (void);
        int SoftwareReset (void);
        int SetDigitalOutput (int lIndex, BOOL bValue);
        int GetDigitalInputs (int *plValue);
        int SetAnalogOutput (int lIndex, int lValue);
        int GetAnalogInput (int lIndex, int *plValue);
        int SetLimit (int lAxis, double dMinRange, double dMaxRange);
        int SetLimitControl (int lAxis, BOOL bActive);
        int GetPos (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetStatus (char *pcStat, int lMaxLen);
        int GetEncoderMask (int *plFlags);
        int StopAxes (void);
        int SetAbortFlag (void);
        int MoveRelSingleAxis (int lAxis, double dValue, BOOL bWait);
        int MoveAbsSingleAxis (int lAxis, double dValue, BOOL bWait);
        int SetControlPars (void);
        int SetMotorCurrent (double dX, double dY, double dZ, double dA);
        int SetVelSingleAxis (int lAxis, double dVel);
        int SetAccelSingleAxis (int lAxis, double dAccel);
        int CalibrateEx (int lFlags);
        int RMeasureEx (int lFlags);
        int SetShowProt (BOOL bShowProt);
        int GetAnalogInputs2 (int *plPT100, int *plMV, int *plV24);
        int SendString (char *pcStr, char *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
        int SetSpeedPoti (BOOL bSpeedPoti);
        int SetTVRMode (int lXT, int lYT, int lZT, int lAT);
        int SetAutoStatus (int lValue);
        int GetStatusAxis (char *pcStatusAxisStr, int lMaxLen);
        int SetDigIO_Off (int lIndex);
        int SetDigIO_Polarity (int lIndex, BOOL bHigh);
        int SetDigIO_EmergencyStop (int lIndex);
        int SetDigIO_Distance (int lIndex, BOOL bFkt, double dDist, int lAxis);
        int SetDimensions (int lXD, int lYD, int lZD, int lAD);
        int MoveRelShort (void);
        int SetEncoderPeriod (double dX, double dY, double dZ, double dA);
        int SetJoystickDir (int lXD, int lYD, int lZD, int lAD);
        int SetEncoderMask (int lValue);
        int SetGear (double dX, double dY, double dZ, double dA);
        int SetHandWheelOn (BOOL bPositionCount, BOOL bEncoder);
        int SetHandWheelOff (void);
        int SetFactorTVR (double dX, double dY, double dZ, double dA);
        int SetTargetWindow (double dX, double dY, double dZ, double dA);
        int SetController (int lXC, int lYC, int lZC, int lAC);
        int SetControllerCall (int lCtrCall);
        int SetControllerSteps (double dX, double dY, double dZ, double dA);
        int SetControllerFactor (double dX, double dY, double dZ, double dA);
        int SetControllerTWDelay (int lCtrTWDelay);
        int SetEncoderRefSignal (int lXR, int lYR, int lZR, int lAR);
        int SetEncoderPosition (BOOL bValue);
        int GetVersionStr (char *pcVers, int lMaxLen);
        int GetError (int *plErrorCode);
        int GetPosSingleAxis (int lAxis, double *pdPos);
        int SetDistance (double dX, double dY, double dZ, double dA);
        int GetPosEx (double *pdX, double *pdY, double *pdZ, double *pdR, BOOL bEncoder);
        int SetShowCmdList (BOOL bShowCmdList);
        int SetWriteLogText (BOOL bAWriteLogText);
        int SetControllerTimeout (int lACtrTimeout);
        int SetEncoderActive (int lFlags);
        int GetSnapshotCount (int *plSnsCount);
        int GetSnapshotPos (double *pdX, double *pdY, double *pdZ, double *pdA);
        int SetCorrTblOff (void);
        int SetCorrTblOn (char *pcAFileName);
        int SetFactorMode (BOOL bAFactorMode, double dX, double dY, double dZ, double dA);
        int SetSnapshot (BOOL bASnapshot);
        int SetSnapshotPar (BOOL bHigh, BOOL bAutoMode);
        int SetTrigger (BOOL bATrigger);
        int SetTriggerPar (int lAxis, int lMode, int lSignal, double dDistance);
        int SetLanguage (char *pcPLN);
        int GetSwitches (int *plFlags);
        int GetSerialNr (char *pcSerialNr, int lMaxLen);
        int SetCalibOffset (double dX, double dY, double dZ, double dR);
        int SetRMOffset (double dX, double dY, double dZ, double dR);
        int GetSnapshotPosArray (int lIndex, double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetAxisDirection (int lXD, int lYD, int lZD, int lAD);
        int SetCalibrateDir (int lXD, int lYD, int lZD, int lAD);
        int LStepSave (void);
        int SetBPZ (int lAValue);
        int SetBPZTrackballFactor (double dAValue);
        int SetBPZTrackballBackLash (double dX, double dY, double dZ, double dR);
        int SetBPZJoyspeed (int lAPar, double dAValue);
        int SetJoystickWindow (int lAValue);
        int SetCurrentDelay (int lX, int lY, int lZ, int lR);
        int MoveEx (double dX, double dY, double dZ, double dR, BOOL bRelative, BOOL bWait, int lAxisCount);
        int WaitForAxisStop (int lAFlags, int lATimeoutValue, BOOL *pbATimeout);
        int SetProcessMessagesProc (void* pProc);
        int SendStringPosCmd (char *pcStr, char *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
        int SetDigitalOutputs (int lValue);
        int SetWriteLogTextFN (BOOL bAWriteLogText, char *pcALogFN);
        int SetDigitalOutputsE (int lValue);
        int GetDigitalInputsE (int *plValue);
        int EnableCommandRetry (BOOL bAValue);
        int SetXYAxisComp (int lValue);
        int GetVersionStrDet (char *pcVersDet, int lMaxLen);
        int GetAPIVersion (char *pcAPIVer, int lMaxLen);
        int SetCommandTimeout (int lAtoRead, int lAtoMove, int lAtoCalibrate);
        int SetExtValue (int lAName, int lAValue);
        int FlushBuffer (int lAValue);
        int GetEEPRomValue (short Offset, short *pValue);
        int SetEEPRomValue (short Offset, short Value);
        int GetXYAxisComp (int *plValue);
        int GetDimensions (int *plXD, int *plYD, int *plZD, int *plAD);
        int GetPitch (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetGear (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetVel (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetAccel (double *pdX, double *pdY, double *pdZ, double *pdA);
        int SetVelFac (double dX, double dY, double dZ, double dR);
        int SetVelFacSingleAxis (int lAxis, double dX, double dY, double dZ, double dR);
        int GetVelFac (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetSpeedPoti (BOOL *pbSpePoti);
        int GetMotorCurrent (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetReduction (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetCurrentDelay (int *plX, int *plY, int *plZ, int *plR);
        int SetOutFuncLev (double dX, double dY, double dZ, double dR);
        int GetOutFuncLev (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetActiveAxes (int *plFlags);
        int GetAxisDirection (int *plXD, int *plYD, int *plZD, int *plAD);
        int GetCalibOffset (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetRMOffset (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetCalibrateDir (int *plXD, int *plYD, int *plZD, int *plAD);
        int SetCalibBackSpeed (int lSpeed);
        int GetCalibBackSpeed (int *plSpeed);
        int SetRefSpeed (int lSpeed);
        int GetRefSpeed (int *plSpeed);
        int SetPowerAmplifier (BOOL bAmplifier);
        int GetPowerAmplifier (BOOL *pbAmplifier);
        int SetMotorTablePatch (BOOL bActive);
        int GetMotorTablePatch (BOOL *pbActive);
        int SetJoystickFilter (BOOL bActive);
        int GetJoystickFilter (BOOL *pbActive);
        int SetStopPolarity (BOOL bHighActiv);
        int GetStopPolarity (BOOL *pbHighActiv);
        int SetVLevel (int lVRegion, double dDownLevel, double dUppLevel);
        int GetVLevel (int lVRegion, double *pdDownLevel, double *pdUppLevel);
        int SetStopAccel (double dXD, double dYD, double dZD, double dAD);
        int GetStopAccel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int GetVersionStrInfo (char *pcVersInfo, int lMaxLen);
        int GetStatusLimit (char *pcLimit, int lMaxLen);
        int GetSecurityErr (DWORD *pdwValue);
        int GetSecurityStatus (DWORD *pdwValue);
        int GetDelay (int *plDelay);
        int GetDistance (double *pdX, double *pdY, double *pdZ, double *pdR);
        int ClearPos (int lFlags);
        int SetDigJoySpeed (double dX, double dY, double dZ, double dR);
        int GetDigJoySpeed (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetJoystickDir (int *plXD, int *plYD, int *plZD, int *plRD);
        int GetJoystick (BOOL *pbJoystickOn, BOOL *pbManual, BOOL *pbPositionCount, BOOL *pbEncoder);
        int GetJoystickWindow (int *plAValue);
        int GetHandWheel (BOOL *pbHandWheelOn, BOOL *pbPositionCount, BOOL *pbEncoder);
        int GetBPZ (int *plAValue);
        int GetBPZTrackballFactor (double *pdAValue);
        int GetBPZTrackballBackLash (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetBPZJoyspeed (int lAPar, double *pdAValue);
        int GetLimitControl (int lAxis, BOOL *pbActive);
        int SetAutoLimitAfterCalibRM (int lFlags);
        int GetAutoLimitAfterCalibRM (int *plFlags);
        int GetSwitchPolarity (int *plXP, int *plYP, int *plZP, int *plRP);
        int GetSwitchActive (int *plXA, int *plYA, int *plZA, int *plRA);
        int GetTVRMode (int *plXT, int *plYT, int *plZT, int *plRT);
        int GetFactorTVR (double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetTVROutMode (int lXT, int lYT, int lZT, int lRT);
        int GetTVROutMode (int *plXT, int *plYT, int *plZT, int *plRT);
        int SetTVROutResolution (int lX, int lY, int lZ, int lR);
        int GetTVROutResolution (int *plX, int *plY, int *plZ, int *plR);
        int SetTVROutPitch (double dX, double dY, double dZ, double dR);
        int GetTVROutPitch (double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetVelTVRO (double dX, double dY, double dZ, double dR);
        int GetVelTVRO (double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetAccelTVRO (double dX, double dY, double dZ, double dR);
        int GetAccelTVRO (double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetVelSingleAxisTVRO (int lAxis, double dVel);
        int SetAccelSingleAxisTVRO (int lAxis, double dAccel);
        int SetPosTVRO (double dX, double dY, double dZ, double dR);
        int GetPosTVRO (double *pdX, double *pdY, double *pdZ, double *pdR);
        int MoveAbsTVRO (double dX, double dY, double dZ, double dR, BOOL bWait);
        int MoveRelTVRO (double dX, double dY, double dZ, double dR, BOOL bWait);
        int MoveRelTVROSingleAxis (int lAxis, double dValue, BOOL bWait);
        int MoveAbsTVROSingleAxis (int lAxis, double dValue, BOOL bWait);
        int GetStatusTVRO (char *pcStat, int lMaxLen);
        int GetTargetWindow (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetEncoderPeriod (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetEncoderRefSignal (int *plXR, int *plYR, int *plZR, int *plRR);
        int GetEncoderPosition (BOOL *pbValue);
        int GetEncoderActive (int *plFlags);
        int GetController (int *plXC, int *plYC, int *plZC, int *plRC);
        int GetControllerCall (int *plCtrCall);
        int GetControllerSteps (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetControllerFactor (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetControllerTWDelay (int *plCtrTWDelay);
        int GetControllerTimeout (int *plACtrTimeout);
        int SetCtrFastMoveOn (void);
        int SetCtrFastMoveOff (void);
        int GetCtrFastMove (BOOL *pbActive);
        int ClearCtrFastMoveCounter (void);
        int GetCtrFastMoveCounter (int *plXC, int *plYC, int *plZC, int *plRC);
        int ClearEncoder (int lAxis);
        int GetEncoder (double *pdXP, double *pdYP, double *pdZP, double *pdRP);
        int GetTrigger (BOOL *pbATrigger);
        int GetTriggerPar (int *plAxis, int *plMode, int *plSignal, double *pdDistance);
        int SetTrigCount (int lValue);
        int GetTrigCount (int *plValue);
        int SetTVRInPulse (int lAxis, BOOL bDirection);
        int GetSnapshot (BOOL *pbASnapshot);
        int SetSnapshotFilter (int lTime);
        int GetSnapshotFilter (int *plTime);
        int GetSnapshotPar (BOOL *pbHigh, BOOL *pbAutoMode);
        int GetLimit (int lAxis, double *pdMinRange, double *pdMaxRange);
        int JoyChangeAxis (BOOL bValue);
        int GetJoyChangeAxis (BOOL *pbValue);
        int SetDigJoyOff (void);
        int SetInputTrigMove (int lMode, BOOL bWait);
        int GetInputTrigMove (int *plMode);
        int SetLimitControlMode (int lMode);
        int GetLimitControlMode (int *plMode);
        int Initialize (char *pcWorkpath);
        int SetAccelJerk (double dXD, double dYD, double dZD, double dAD);
        int SetDecelJerk (double dXD, double dYD, double dZD, double dAD);
        int SetCalibRMJerk (double dXD, double dYD, double dZD, double dAD);
        int SetJoyVel (double dXD, double dYD, double dZD, double dAD);
        int GetJoyVel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetDeceleration (double dXD, double dYD, double dZD, double dAD);
        int GetDeceleration (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetDecelSingleAxis (int lAxis, double dValue);
        int ConfigMaxAxes (int lnAxes);
        int SetJoystickAxes (int lFlags);
        int GetJoystickAxes (int *plFlags);
        int SetJoyVelSkal (int lX, int lY, int lZ, int lR);
        int GetJoyVelSkal (int *plX, int *plY, int *plZ, int *plR);
        int SetMaxUserCurrent (double dXD, double dYD, double dZD, double dAD);
        int GetMaxUserCurrent (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetStopDecel (double dXD, double dYD, double dZD, double dAD);
        int GetStopDecel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetMotorMaxVel (double dXD, double dYD, double dZD, double dAD);
        int GetMotorMaxVel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetMotorStandForce (double dXD, double dYD, double dZD, double dAD);
        int GetMotorStandForce (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetMotorStandMoment (double dXD, double dYD, double dZD, double dAD);
        int GetMotorStandMoment (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetMotorFieldDir (int lX, int lY, int lZ, int lA);
        int GetMotorFieldDir (int *plX, int *plY, int *plZ, int *plA);
        int SetMotorType (int lX, int lY, int lZ, int lA);
        int GetMotorType (int *plX, int *plY, int *plZ, int *plA);
        int SetOsziCallBackFct (void* pFct);
        int SetCalibRMAccel (double dXD, double dYD, double dZD, double dAD);
        int GetCalibRMAccel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int GetCalibRMJerk (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetCalibRMVel (double dXD, double dYD, double dZD, double dAD);
        int GetCalibRMVel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetCalibRMBackSpeed (double dXD, double dYD, double dZD, double dAD);
        int GetCalibRMBackSpeed (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int GetAccelJerk (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int GetDecelJerk (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetGearDenominator (int lX, int lY, int lZ, int lR);
        int GetGearDenominator (int *plX, int *plY, int *plZ, int *plR);
        int SetGearNumerator (int lX, int lY, int lZ, int lR);
        int GetGearNumerator (int *plX, int *plY, int *plZ, int *plR);
        int SetStopDecelJerk (double dXD, double dYD, double dZD, double dAD);
        int GetStopDecelJerk (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetSwChange (int lFlags);
        int GetSwChange (int *plFlags);
 
#ifdef __cplusplus
    }
#endif

#endif // __CLStep4__
