// Headerdatei für CLStep4X

#ifndef __CLStep4X__
#define __CLStep4X__


/////////////////////////////////////////////////////////////////////////////////////////////
// C-Kapselung für LStep4X.DLL

const int XAxis = 1;
const int YAxis = 2;
const int ZAxis = 3;
const int AAxis = 4;

#pragma pack(1)
struct TLS_ControlInitPar
{
      int Size;
      int InterfaceType;
      char ComNameLength;
      char ComName[32];
      BOOL ShowProt;
      BOOL ShowCmdList;

      int BaudRate;
      int IOAdress;
      int CardIndex;

      int ControlType;
      char VersionStrLength;
      char VersionStr[64];
      int Axes;
      int ErrorCode;
      BOOL NewCmds;
      int Encoder;
      BOOL Display, SpeedPoti, HandWheel, Snapshot, TVR, TriggerOut;
      BOOL DemoMode;
};
#pragma pack(8)

#pragma pack(1)
struct TLS_ControlInitParW
{
      int Size;
      int InterfaceType;
      TCHAR ComNameW[32];
      BOOL ShowProt;
      BOOL ShowCmdList;

      int BaudRate;
      int IOAdress;
      int CardIndex;

      int ControlType;
      TCHAR VersionStrW[64];
      int Axes;
      int ErrorCode;
      BOOL NewCmds;
      int Encoder;
      BOOL Display, SpeedPoti, HandWheel, Snapshot, TVR, TriggerOut;
      BOOL DemoMode;
};
#pragma pack(8)


typedef int (__stdcall *PConnect) (int lLSID);
typedef int (__stdcall *PConnectSimple) (int lLSID, int lAnInterfaceType, char *pcAComName, int lABaudRate, BOOL bAShowProt);
typedef int (__stdcall *PConnectSimpleW) (int lLSID, int lAnInterfaceType, TCHAR *pcAComName, int lABaudRate, BOOL bAShowProt);
typedef int (__stdcall *PConnectEx) (int lLSID, struct TLS_ControlInitPar *pAControlInitPar);
typedef int (__stdcall *PConnectExW) (int lLSID, struct TLS_ControlInitParW *pAControlInitPar);
typedef int (__stdcall *PDisconnect) (int lLSID);
typedef int (__stdcall *PLoadConfig) (int lLSID, char *pcFileName);
typedef int (__stdcall *PLoadConfigW) (int lLSID, TCHAR *pcFileName);
typedef int (__stdcall *PSaveConfig) (int lLSID, char *pcFileName);
typedef int (__stdcall *PSaveConfigW) (int lLSID, TCHAR *pcFileName);
typedef int (__stdcall *PMoveAbs) (int lLSID, double dX, double dY, double dZ, double dA, BOOL bWait);
typedef int (__stdcall *PMoveRel) (int lLSID, double dX, double dY, double dZ, double dA, BOOL bWait);
typedef int (__stdcall *PCalibrate) (int lLSID);
typedef int (__stdcall *PRMeasure) (int lLSID);
typedef int (__stdcall *PSetPitch) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetPos) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetActiveAxes) (int lLSID, int lFlags);
typedef int (__stdcall *PSetVel) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetAccel) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetReduction) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetDelay) (int lLSID, int lDelay);
typedef int (__stdcall *PSetSwitchPolarity) (int lLSID, int lXP, int lYP, int lZP, int lAP);
typedef int (__stdcall *PSetSwitchActive) (int lLSID, int lXA, int lYA, int lZA, int lAA);
typedef int (__stdcall *PSetJoystickOn) (int lLSID, BOOL bPositionCount, BOOL bEncoder);
typedef int (__stdcall *PSetJoystickOff) (int lLSID);
typedef int (__stdcall *PSoftwareReset) (int lLSID);
typedef int (__stdcall *PSetDigitalOutput) (int lLSID, int lIndex, BOOL bValue);
typedef int (__stdcall *PGetDigitalInputs) (int lLSID, int *plValue);
typedef int (__stdcall *PSetAnalogOutput) (int lLSID, int lIndex, int lValue);
typedef int (__stdcall *PGetAnalogInput) (int lLSID, int lIndex, int *plValue);
typedef int (__stdcall *PSetLimit) (int lLSID, int lAxis, double dMinRange, double dMaxRange);
typedef int (__stdcall *PSetLimitControl) (int lLSID, int lAxis, BOOL bActive);
typedef int (__stdcall *PGetPos) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetStatus) (int lLSID, char *pcStat, int lMaxLen);
typedef int (__stdcall *PGetStatusW) (int lLSID, TCHAR *pcStat, int lMaxLen);
typedef int (__stdcall *PGetEncoderMask) (int lLSID, int *plFlags);
typedef int (__stdcall *PStopAxes) (int lLSID);
typedef int (__stdcall *PSetAbortFlag) (int lLSID);
typedef int (__stdcall *PMoveRelSingleAxis) (int lLSID, int lAxis, double dValue, BOOL bWait);
typedef int (__stdcall *PMoveAbsSingleAxis) (int lLSID, int lAxis, double dValue, BOOL bWait);
typedef int (__stdcall *PMoveSequence) (int lLSID, int lnMode, BOOL bWait);
typedef int (__stdcall *PSetControlPars) (int lLSID);
typedef int (__stdcall *PSetMotorCurrent) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetVelSingleAxis) (int lLSID, int lAxis, double dVel);
typedef int (__stdcall *PSetAccelSingleAxis) (int lLSID, int lAxis, double dAccel);
typedef int (__stdcall *PCalibrateEx) (int lLSID, int lFlags);
typedef int (__stdcall *PRMeasureEx) (int lLSID, int lFlags);
typedef int (__stdcall *PSetShowProt) (int lLSID, BOOL bShowProt);
typedef int (__stdcall *PGetAnalogInputs2) (int lLSID, int *plPT100, int *plMV, int *plV24);
typedef int (__stdcall *PSendString) (int lLSID, char *pcStr, char *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
typedef int (__stdcall *PSendStringW) (int lLSID, TCHAR *pcStr, TCHAR *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
typedef int (__stdcall *PSetSpeedPoti) (int lLSID, BOOL bSpeedPoti);
typedef int (__stdcall *PSetTVRMode) (int lLSID, int lXT, int lYT, int lZT, int lAT);
typedef int (__stdcall *PSetAutoStatus) (int lLSID, int lValue);
typedef int (__stdcall *PGetStatusAxis) (int lLSID, char *pcStatusAxisStr, int lMaxLen);
typedef int (__stdcall *PGetStatusAxisW) (int lLSID, TCHAR *pcStatusAxisStr, int lMaxLen);
typedef int (__stdcall *PSetDigIO_Off) (int lLSID, int lIndex);
typedef int (__stdcall *PSetDigIO_Polarity) (int lLSID, int lIndex, BOOL bHigh);
typedef int (__stdcall *PSetDigIO_EmergencyStop) (int lLSID, int lIndex);
typedef int (__stdcall *PSetDigIO_Distance) (int lLSID, int lIndex, BOOL bFkt, double dDist, int lAxis);
typedef int (__stdcall *PSetDimensions) (int lLSID, int lXD, int lYD, int lZD, int lAD);
typedef int (__stdcall *PMoveRelShort) (int lLSID);
typedef int (__stdcall *PSetEncoderPeriod) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetJoystickDir) (int lLSID, int lXD, int lYD, int lZD, int lAD);
typedef int (__stdcall *PSetEncoderMask) (int lLSID, int lValue);
typedef int (__stdcall *PSetGear) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetHandWheelOn) (int lLSID, BOOL bPositionCount, BOOL bEncoder);
typedef int (__stdcall *PSetHandWheelOff) (int lLSID);
typedef int (__stdcall *PSetFactorTVR) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetController) (int lLSID, int lXC, int lYC, int lZC, int lAC);
typedef int (__stdcall *PSetControllerCall) (int lLSID, int lCtrCall);
typedef int (__stdcall *PSetControllerSteps) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetControllerFactor) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetControllerTWDelay) (int lLSID, int lCtrTWDelay);
typedef int (__stdcall *PSetEncoderRefSignal) (int lLSID, int lXR, int lYR, int lZR, int lAR);
typedef int (__stdcall *PSetEncoderPosition) (int lLSID, BOOL bValue);
typedef int (__stdcall *PGetVersionStr) (int lLSID, char *pcVers, int lMaxLen);
typedef int (__stdcall *PGetVersionStrW) (int lLSID, TCHAR *pcVers, int lMaxLen);
typedef int (__stdcall *PGetError) (int lLSID, int *plErrorCode);
typedef int (__stdcall *PGetPosSingleAxis) (int lLSID, int lAxis, double *pdPos);
typedef int (__stdcall *PSetDistance) (int lLSID, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PGetPosEx) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR, BOOL bEncoder);
typedef int (__stdcall *PSetShowCmdList) (int lLSID, BOOL bShowCmdList);
typedef int (__stdcall *PSetWriteLogText) (int lLSID, BOOL bAWriteLogText);
typedef int (__stdcall *PSetControllerTimeout) (int lLSID, int lACtrTimeout);
typedef int (__stdcall *PSetEncoderActive) (int lLSID, int lFlags);
typedef int (__stdcall *PGetSnapshotCount) (int lLSID, int *plSnsCount);
typedef int (__stdcall *PGetSnapshotPos) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PSetCorrTblOff) (int lLSID);
typedef int (__stdcall *PSetCorrTblOn) (int lLSID, char *pcAFileName);
typedef int (__stdcall *PSetCorrTblOnW) (int lLSID, TCHAR *pcAFileName);
typedef int (__stdcall *PSetFactorMode) (int lLSID, BOOL bAFactorMode, double dX, double dY, double dZ, double dA);
typedef int (__stdcall *PSetSnapshot) (int lLSID, BOOL bASnapshot);
typedef int (__stdcall *PSetSnapshotPar) (int lLSID, BOOL bHigh, BOOL bAutoMode);
typedef int (__stdcall *PSetTrigger) (int lLSID, BOOL bATrigger);
typedef int (__stdcall *PSetTriggerPar) (int lLSID, int lAxis, int lMode, int lSignal, double dDistance);
typedef int (__stdcall *PSetLanguage) (int lLSID, char *pcPLN);
typedef int (__stdcall *PSetLanguageW) (int lLSID, TCHAR *pcPLN);
typedef int (__stdcall *PGetSwitches) (int lLSID, int *plFlags);
typedef int (__stdcall *PGetSerialNr) (int lLSID, char *pcSerialNr, int lMaxLen);
typedef int (__stdcall *PGetSerialNrW) (int lLSID, TCHAR *pcSerialNr, int lMaxLen);
typedef int (__stdcall *PSetCalibOffset) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PSetRMOffset) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetSnapshotPosArray) (int lLSID, int lIndex, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetAxisDirection) (int lLSID, int lXD, int lYD, int lZD, int lAD);
typedef int (__stdcall *PSetCalibrateDir) (int lLSID, int lXD, int lYD, int lZD, int lAD);
typedef int (__stdcall *PLStepSave) (int lLSID);
typedef int (__stdcall *PSetBPZ) (int lLSID, int lAValue);
typedef int (__stdcall *PSetBPZTrackballFactor) (int lLSID, double dAValue);
typedef int (__stdcall *PSetBPZTrackballBackLash) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PSetBPZJoyspeed) (int lLSID, int lAPar, double dAValue);
typedef int (__stdcall *PSetJoystickWindow) (int lLSID, int lAValue);
typedef int (__stdcall *PSetCurrentDelay) (int lLSID, int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PMoveEx) (int lLSID, double dX, double dY, double dZ, double dR, BOOL bRelative, BOOL bWait, int lAxisCount);
typedef int (__stdcall *PWaitForAxisStop) (int lLSID, int lAFlags, int lATimeoutValue, BOOL *pbATimeout);
typedef int (__stdcall *PSendStringPosCmd) (int lLSID, char *pcStr, char *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
typedef int (__stdcall *PSendStringPosCmdW) (int lLSID, TCHAR *pcStr, TCHAR *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
typedef int (__stdcall *PSetDigitalOutputs) (int lLSID, int lValue);
typedef int (__stdcall *PSetWriteLogTextFN) (int lLSID, BOOL bAWriteLogText, char *pcALogFN);
typedef int (__stdcall *PSetWriteLogTextFNW) (int lLSID, BOOL bAWriteLogText, TCHAR *pcALogFN);
typedef int (__stdcall *PSetDigitalOutputsE) (int lLSID, int lValue);
typedef int (__stdcall *PGetDigitalInputsE) (int lLSID, int *plValue);
typedef int (__stdcall *PEnableCommandRetry) (int lLSID, BOOL bAValue);
typedef int (__stdcall *PSetXYAxisComp) (int lLSID, int lValue);
typedef int (__stdcall *PGetVersionStrDet) (int lLSID, char *pcVersDet, int lMaxLen);
typedef int (__stdcall *PGetVersionStrDetW) (int lLSID, TCHAR *pcVersDet, int lMaxLen);
typedef int (__stdcall *PGetAPIVersion) (int lLSID, char *pcAPIVer, int lMaxLen);
typedef int (__stdcall *PGetAPIVersionW) (int lLSID, TCHAR *pcAPIVer, int lMaxLen);
typedef int (__stdcall *PSetCommandTimeout) (int lLSID, int lAtoRead, int lAtoMove, int lAtoCalibrate);
typedef int (__stdcall *PSetExtValue) (int lLSID, int lAName, int lAValue);
typedef int (__stdcall *PFlushBuffer) (int lLSID, int lAValue);
typedef int (__stdcall *PSetProcessMessagesProc) (int lLSID, void* pProc);
typedef int (__stdcall *PGetEEPRomValue) (int lLSID, byte Offset, byte *pValue);
typedef int (__stdcall *PSetEEPRomValue) (int lLSID, byte Offset, byte Value);
typedef int (__stdcall *PGetXYAxisComp) (int lLSID, int *plValue);
typedef int (__stdcall *PGetDimensions) (int lLSID, int *plXD, int *plYD, int *plZD, int *plAD);
typedef int (__stdcall *PGetPitch) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetGear) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetVel) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetAccel) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PSetVelFac) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PSetVelFacSingleAxis) (int lLSID, int lAxis, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetVelFac) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetSpeedPoti) (int lLSID, BOOL *pbSpePoti);
typedef int (__stdcall *PGetMotorCurrent) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetReduction) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdA);
typedef int (__stdcall *PGetCurrentDelay) (int lLSID, int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetOutFuncLev) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetOutFuncLev) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetActiveAxes) (int lLSID, int *plFlags);
typedef int (__stdcall *PGetAxisDirection) (int lLSID, int *plXD, int *plYD, int *plZD, int *plAD);
typedef int (__stdcall *PGetCalibOffset) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetRMOffset) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetCalibrateDir) (int lLSID, int *plXD, int *plYD, int *plZD, int *plAD);
typedef int (__stdcall *PSetCalibBackSpeed) (int lLSID, int lSpeed);
typedef int (__stdcall *PGetCalibBackSpeed) (int lLSID, int *plSpeed);
typedef int (__stdcall *PSetRefSpeed) (int lLSID, int lSpeed);
typedef int (__stdcall *PGetRefSpeed) (int lLSID, int *plSpeed);
typedef int (__stdcall *PSetPowerAmplifier) (int lLSID, BOOL bAmplifier);
typedef int (__stdcall *PGetPowerAmplifier) (int lLSID, BOOL *pbAmplifier);
typedef int (__stdcall *PSetMotorTablePatch) (int lLSID, BOOL bActive);
typedef int (__stdcall *PGetMotorTablePatch) (int lLSID, BOOL *pbActive);
typedef int (__stdcall *PSetJoystickFilter) (int lLSID, BOOL bActive);
typedef int (__stdcall *PGetJoystickFilter) (int lLSID, BOOL *pbActive);
typedef int (__stdcall *PSetStopPolarity) (int lLSID, BOOL bHighActiv);
typedef int (__stdcall *PGetStopPolarity) (int lLSID, BOOL *pbHighActiv);
typedef int (__stdcall *PSetVLevel) (int lLSID, int lVRegion, double dDownLevel, double dUppLevel);
typedef int (__stdcall *PGetVLevel) (int lLSID, int lVRegion, double *pdDownLevel, double *pdUppLevel);
typedef int (__stdcall *PSetStopAccel) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetStopAccel) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PGetVersionStrInfo) (int lLSID, char *pcVersInfo, int lMaxLen);
typedef int (__stdcall *PGetVersionStrInfoW) (int lLSID, TCHAR *pcVersInfo, int lMaxLen);
typedef int (__stdcall *PGetStatusLimit) (int lLSID, char *pcLimit, int lMaxLen);
typedef int (__stdcall *PGetStatusLimitW) (int lLSID, TCHAR *pcLimit, int lMaxLen);
typedef int (__stdcall *PGetSecurityErr) (int lLSID, DWORD *pdwValue);
typedef int (__stdcall *PGetSecurityStatus) (int lLSID, DWORD *pdwValue);
typedef int (__stdcall *PGetDelay) (int lLSID, int *plDelay);
typedef int (__stdcall *PGetDistance) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PClearPos) (int lLSID, int lFlags);
typedef int (__stdcall *PSetDigJoySpeed) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetDigJoySpeed) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetJoystickDir) (int lLSID, int *plXD, int *plYD, int *plZD, int *plRD);
typedef int (__stdcall *PGetJoystick) (int lLSID, BOOL *pbJoystickOn, BOOL *pbManual, BOOL *pbPositionCount, BOOL *pbEncoder);
typedef int (__stdcall *PGetJoystickWindow) (int lLSID, int *plAValue);
typedef int (__stdcall *PGetHandWheel) (int lLSID, BOOL *pbHandWheelOn, BOOL *pbPositionCount, BOOL *pbEncoder);
typedef int (__stdcall *PGetBPZ) (int lLSID, int *plAValue);
typedef int (__stdcall *PGetBPZTrackballFactor) (int lLSID, double *pdAValue);
typedef int (__stdcall *PGetBPZTrackballBackLash) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetBPZJoyspeed) (int lLSID, int lAPar, double *pdAValue);
typedef int (__stdcall *PGetLimitControl) (int lLSID, int lAxis, BOOL *pbActive);
typedef int (__stdcall *PSetAutoLimitAfterCalibRM) (int lLSID, int lFlags);
typedef int (__stdcall *PGetAutoLimitAfterCalibRM) (int lLSID, int *plFlags);
typedef int (__stdcall *PGetSwitchPolarity) (int lLSID, int *plXP, int *plYP, int *plZP, int *plRP);
typedef int (__stdcall *PGetSwitchActive) (int lLSID, int *plXA, int *plYA, int *plZA, int *plRA);
typedef int (__stdcall *PGetTVRMode) (int lLSID, int *plXT, int *plYT, int *plZT, int *plRT);
typedef int (__stdcall *PGetFactorTVR) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetTVROutMode) (int lLSID, int lXT, int lYT, int lZT, int lRT);
typedef int (__stdcall *PGetTVROutMode) (int lLSID, int *plXT, int *plYT, int *plZT, int *plRT);
typedef int (__stdcall *PSetTVROutResolution) (int lLSID, int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PGetTVROutResolution) (int lLSID, int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetTVROutPitch) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetTVROutPitch) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetVelTVRO) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetVelTVRO) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetAccelTVRO) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetAccelTVRO) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PSetVelSingleAxisTVRO) (int lLSID, int lAxis, double dVel);
typedef int (__stdcall *PSetAccelSingleAxisTVRO) (int lLSID, int lAxis, double dAccel);
typedef int (__stdcall *PSetPosTVRO) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetPosTVRO) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PMoveAbsTVRO) (int lLSID, double dX, double dY, double dZ, double dR, BOOL bWait);
typedef int (__stdcall *PMoveRelTVRO) (int lLSID, double dX, double dY, double dZ, double dR, BOOL bWait);
typedef int (__stdcall *PMoveRelTVROSingleAxis) (int lLSID, int lAxis, double dValue, BOOL bWait);
typedef int (__stdcall *PMoveAbsTVROSingleAxis) (int lLSID, int lAxis, double dValue, BOOL bWait);
typedef int (__stdcall *PGetStatusTVRO) (int lLSID, char *pcStat, int lMaxLen);
typedef int (__stdcall *PGetStatusTVROW) (int lLSID, TCHAR *pcStat, int lMaxLen);
typedef int (__stdcall *PSetTargetWindow) (int lLSID, double dX, double dY, double dZ, double dR);
typedef int (__stdcall *PGetTargetWindow) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetEncoderPeriod) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetEncoderRefSignal) (int lLSID, int *plXR, int *plYR, int *plZR, int *plRR);
typedef int (__stdcall *PGetEncoderPosition) (int lLSID, BOOL *pbValue);
typedef int (__stdcall *PGetEncoderActive) (int lLSID, int *plFlags);
typedef int (__stdcall *PGetController) (int lLSID, int *plXC, int *plYC, int *plZC, int *plRC);
typedef int (__stdcall *PGetControllerCall) (int lLSID, int *plCtrCall);
typedef int (__stdcall *PGetControllerSteps) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetControllerFactor) (int lLSID, double *pdX, double *pdY, double *pdZ, double *pdR);
typedef int (__stdcall *PGetControllerTWDelay) (int lLSID, int *plCtrTWDelay);
typedef int (__stdcall *PGetControllerTimeout) (int lLSID, int *plACtrTimeout);
typedef int (__stdcall *PSetCtrFastMoveOn) (int lLSID);
typedef int (__stdcall *PSetCtrFastMoveOff) (int lLSID);
typedef int (__stdcall *PGetCtrFastMove) (int lLSID, BOOL *pbActive);
typedef int (__stdcall *PClearCtrFastMoveCounter) (int lLSID);
typedef int (__stdcall *PGetCtrFastMoveCounter) (int lLSID, int *plXC, int *plYC, int *plZC, int *plRC);
typedef int (__stdcall *PClearEncoder) (int lLSID, int lAxis);
typedef int (__stdcall *PGetEncoder) (int lLSID, double *pdXP, double *pdYP, double *pdZP, double *pdRP);
typedef int (__stdcall *PGetTrigger) (int lLSID, BOOL *pbATrigger);
typedef int (__stdcall *PGetTriggerPar) (int lLSID, int *plAxis, int *plMode, int *plSignal, double *pdDistance);
typedef int (__stdcall *PSetTrigCount) (int lLSID, int lValue);
typedef int (__stdcall *PGetTrigCount) (int lLSID, int *plValue);
typedef int (__stdcall *PSetTVRInPulse) (int lLSID, int lAxis, BOOL bDirection);
typedef int (__stdcall *PGetSnapshot) (int lLSID, BOOL *pbASnapshot);
typedef int (__stdcall *PSetSnapshotFilter) (int lLSID, int lTime);
typedef int (__stdcall *PGetSnapshotFilter) (int lLSID, int *plTime);
typedef int (__stdcall *PGetSnapshotPar) (int lLSID, BOOL *pbHigh, BOOL *pbAutoMode);
typedef int (__stdcall *PGetLimit) (int lLSID, int lAxis, double *pdMinRange, double *pdMaxRange);
typedef int (__stdcall *PJoyChangeAxis) (int lLSID, BOOL bValue);
typedef int (__stdcall *PGetJoyChangeAxis) (int lLSID, BOOL *pbValue);
typedef int (__stdcall *PSetDigJoyOff) (int lLSID);
typedef int (__stdcall *PSetInputTrigMove) (int lLSID, int lMode, BOOL bWait);
typedef int (__stdcall *PGetInputTrigMove) (int lLSID, int *plMode);
typedef int (__stdcall *PSetLimitControlMode) (int lLSID, int lMode);
typedef int (__stdcall *PGetLimitControlMode) (int lLSID, int *plMode);
typedef int (__stdcall *PInitialize) (int lLSID, char *pcWorkpath);
typedef int (__stdcall *PInitializeW) (int lLSID, TCHAR *pcWorkpath);
typedef int (__stdcall *PSetAccelJerk) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PSetDecelJerk) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PSetCalibRMJerk) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PSetJoyVel) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetJoyVel) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetDeceleration) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetDeceleration) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetDecelSingleAxis) (int lLSID, int lAxis, double dValue);
typedef int (__stdcall *PConfigMaxAxes) (int lLSID, int lnAxes);
typedef int (__stdcall *PSetJoystickAxes) (int lLSID, int lFlags);
typedef int (__stdcall *PGetJoystickAxes) (int lLSID, int *plFlags);
typedef int (__stdcall *PSetJoyVelSkal) (int lLSID, int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PGetJoyVelSkal) (int lLSID, int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetMaxUserCurrent) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetMaxUserCurrent) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetStopDecel) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetStopDecel) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetMotorMaxVel) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetMotorMaxVel) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetMotorStandForce) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetMotorStandForce) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetMotorStandMoment) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetMotorStandMoment) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetMotorFieldDir) (int lLSID, int lX, int lY, int lZ, int lA);
typedef int (__stdcall *PGetMotorFieldDir) (int lLSID, int *plX, int *plY, int *plZ, int *plA);
typedef int (__stdcall *PSetMotorType) (int lLSID, int lX, int lY, int lZ, int lA);
typedef int (__stdcall *PGetMotorType) (int lLSID, int *plX, int *plY, int *plZ, int *plA);
typedef int (__stdcall *PSetOsziCallBackFct) (int lLSID, void* pFct);
typedef int (__stdcall *PTranslateErrMsg) (int lLSID, TCHAR *pcMsgIn, TCHAR *pcMsgOut, int lMaxLen);
typedef int (__stdcall *PSetCalibRMAccel) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetCalibRMAccel) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PGetCalibRMJerk) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetCalibRMVel) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetCalibRMVel) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetCalibRMBackSpeed) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetCalibRMBackSpeed) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PGetAccelJerk) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PGetDecelJerk) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetGearDenominator) (int lLSID, int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PGetGearDenominator) (int lLSID, int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetGearNumerator) (int lLSID, int lX, int lY, int lZ, int lR);
typedef int (__stdcall *PGetGearNumerator) (int lLSID, int *plX, int *plY, int *plZ, int *plR);
typedef int (__stdcall *PSetStopDecelJerk) (int lLSID, double dXD, double dYD, double dZD, double dAD);
typedef int (__stdcall *PGetStopDecelJerk) (int lLSID, double *pdXD, double *pdYD, double *pdZD, double *pdAD);
typedef int (__stdcall *PSetSwChange) (int lLSID, int lFlags);
typedef int (__stdcall *PGetSwChange) (int lLSID, int *plFlags);
typedef int (__stdcall *PCreateLSID) (int *plLSID);
typedef int (__stdcall *PFreeLSID) (int lLSID);

/*
class CLStep4X
{

	int			m_DLLResultat;			// DLL-Zugriff ok
	HINSTANCE	        m_LStep4;	                // Handle auf Dll
	int			m_LSID;			        // DLL-Zugriff ok

        // Zeiger Funktion in DLL
        PConnect m_pConnect;
        PConnectSimple m_pConnectSimple;
        PConnectSimpleW m_pConnectSimpleW;
        PConnectEx m_pConnectEx;
        PConnectExW m_pConnectExW;
        PDisconnect m_pDisconnect;
        PLoadConfig m_pLoadConfig;
        PLoadConfigW m_pLoadConfigW;
        PSaveConfig m_pSaveConfig;
        PSaveConfigW m_pSaveConfigW;
        PMoveAbs m_pMoveAbs;
        PMoveRel m_pMoveRel;
        PCalibrate m_pCalibrate;
        PRMeasure m_pRMeasure;
        PSetPitch m_pSetPitch;
        PSetPos m_pSetPos;
        PSetActiveAxes m_pSetActiveAxes;
        PSetVel m_pSetVel;
        PSetAccel m_pSetAccel;
        PSetReduction m_pSetReduction;
        PSetDelay m_pSetDelay;
        PSetSwitchPolarity m_pSetSwitchPolarity;
        PSetSwitchActive m_pSetSwitchActive;
        PSetJoystickOn m_pSetJoystickOn;
        PSetJoystickOff m_pSetJoystickOff;
        PSoftwareReset m_pSoftwareReset;
        PSetDigitalOutput m_pSetDigitalOutput;
        PGetDigitalInputs m_pGetDigitalInputs;
        PSetAnalogOutput m_pSetAnalogOutput;
        PGetAnalogInput m_pGetAnalogInput;
        PSetLimit m_pSetLimit;
        PSetLimitControl m_pSetLimitControl;
        PGetPos m_pGetPos;
        PGetStatus m_pGetStatus;
        PGetStatusW m_pGetStatusW;
        PGetEncoderMask m_pGetEncoderMask;
        PStopAxes m_pStopAxes;
        PSetAbortFlag m_pSetAbortFlag;
        PMoveRelSingleAxis m_pMoveRelSingleAxis;
        PMoveAbsSingleAxis m_pMoveAbsSingleAxis;
        PMoveSequence m_pMoveSequence;
        PSetControlPars m_pSetControlPars;
        PSetMotorCurrent m_pSetMotorCurrent;
        PSetVelSingleAxis m_pSetVelSingleAxis;
        PSetAccelSingleAxis m_pSetAccelSingleAxis;
        PCalibrateEx m_pCalibrateEx;
        PRMeasureEx m_pRMeasureEx;
        PSetShowProt m_pSetShowProt;
        PGetAnalogInputs2 m_pGetAnalogInputs2;
        PSendString m_pSendString;
        PSendStringW m_pSendStringW;
        PSetSpeedPoti m_pSetSpeedPoti;
        PSetTVRMode m_pSetTVRMode;
        PSetAutoStatus m_pSetAutoStatus;
        PGetStatusAxis m_pGetStatusAxis;
        PGetStatusAxisW m_pGetStatusAxisW;
        PSetDigIO_Off m_pSetDigIO_Off;
        PSetDigIO_Polarity m_pSetDigIO_Polarity;
        PSetDigIO_EmergencyStop m_pSetDigIO_EmergencyStop;
        PSetDigIO_Distance m_pSetDigIO_Distance;
        PSetDimensions m_pSetDimensions;
        PMoveRelShort m_pMoveRelShort;
        PSetEncoderPeriod m_pSetEncoderPeriod;
        PSetJoystickDir m_pSetJoystickDir;
        PSetEncoderMask m_pSetEncoderMask;
        PSetGear m_pSetGear;
        PSetHandWheelOn m_pSetHandWheelOn;
        PSetHandWheelOff m_pSetHandWheelOff;
        PSetFactorTVR m_pSetFactorTVR;
        PSetController m_pSetController;
        PSetControllerCall m_pSetControllerCall;
        PSetControllerSteps m_pSetControllerSteps;
        PSetControllerFactor m_pSetControllerFactor;
        PSetControllerTWDelay m_pSetControllerTWDelay;
        PSetEncoderRefSignal m_pSetEncoderRefSignal;
        PSetEncoderPosition m_pSetEncoderPosition;
        PGetVersionStr m_pGetVersionStr;
        PGetVersionStrW m_pGetVersionStrW;
        PGetError m_pGetError;
        PGetPosSingleAxis m_pGetPosSingleAxis;
        PSetDistance m_pSetDistance;
        PGetPosEx m_pGetPosEx;
        PSetShowCmdList m_pSetShowCmdList;
        PSetWriteLogText m_pSetWriteLogText;
        PSetControllerTimeout m_pSetControllerTimeout;
        PSetEncoderActive m_pSetEncoderActive;
        PGetSnapshotCount m_pGetSnapshotCount;
        PGetSnapshotPos m_pGetSnapshotPos;
        PSetCorrTblOff m_pSetCorrTblOff;
        PSetCorrTblOn m_pSetCorrTblOn;
        PSetCorrTblOnW m_pSetCorrTblOnW;
        PSetFactorMode m_pSetFactorMode;
        PSetSnapshot m_pSetSnapshot;
        PSetSnapshotPar m_pSetSnapshotPar;
        PSetTrigger m_pSetTrigger;
        PSetTriggerPar m_pSetTriggerPar;
        PSetLanguage m_pSetLanguage;
        PSetLanguageW m_pSetLanguageW;
        PGetSwitches m_pGetSwitches;
        PGetSerialNr m_pGetSerialNr;
        PGetSerialNrW m_pGetSerialNrW;
        PSetCalibOffset m_pSetCalibOffset;
        PSetRMOffset m_pSetRMOffset;
        PGetSnapshotPosArray m_pGetSnapshotPosArray;
        PSetAxisDirection m_pSetAxisDirection;
        PSetCalibrateDir m_pSetCalibrateDir;
        PLStepSave m_pLStepSave;
        PSetBPZ m_pSetBPZ;
        PSetBPZTrackballFactor m_pSetBPZTrackballFactor;
        PSetBPZTrackballBackLash m_pSetBPZTrackballBackLash;
        PSetBPZJoyspeed m_pSetBPZJoyspeed;
        PSetJoystickWindow m_pSetJoystickWindow;
        PSetCurrentDelay m_pSetCurrentDelay;
        PMoveEx m_pMoveEx;
        PWaitForAxisStop m_pWaitForAxisStop;
        PSendStringPosCmd m_pSendStringPosCmd;
        PSendStringPosCmdW m_pSendStringPosCmdW;
        PSetDigitalOutputs m_pSetDigitalOutputs;
        PSetWriteLogTextFN m_pSetWriteLogTextFN;
        PSetWriteLogTextFNW m_pSetWriteLogTextFNW;
        PSetDigitalOutputsE m_pSetDigitalOutputsE;
        PGetDigitalInputsE m_pGetDigitalInputsE;
        PEnableCommandRetry m_pEnableCommandRetry;
        PSetXYAxisComp m_pSetXYAxisComp;
        PGetVersionStrDet m_pGetVersionStrDet;
        PGetVersionStrDetW m_pGetVersionStrDetW;
        PGetAPIVersion m_pGetAPIVersion;
        PGetAPIVersionW m_pGetAPIVersionW;
        PSetCommandTimeout m_pSetCommandTimeout;
        PSetExtValue m_pSetExtValue;
        PFlushBuffer m_pFlushBuffer;
        PSetProcessMessagesProc m_pSetProcessMessagesProc;
        PGetEEPRomValue m_pGetEEPRomValue;
        PSetEEPRomValue m_pSetEEPRomValue;
        PGetXYAxisComp m_pGetXYAxisComp;
        PGetDimensions m_pGetDimensions;
        PGetPitch m_pGetPitch;
        PGetGear m_pGetGear;
        PGetVel m_pGetVel;
        PGetAccel m_pGetAccel;
        PSetVelFac m_pSetVelFac;
        PSetVelFacSingleAxis m_pSetVelFacSingleAxis;
        PGetVelFac m_pGetVelFac;
        PGetSpeedPoti m_pGetSpeedPoti;
        PGetMotorCurrent m_pGetMotorCurrent;
        PGetReduction m_pGetReduction;
        PGetCurrentDelay m_pGetCurrentDelay;
        PSetOutFuncLev m_pSetOutFuncLev;
        PGetOutFuncLev m_pGetOutFuncLev;
        PGetActiveAxes m_pGetActiveAxes;
        PGetAxisDirection m_pGetAxisDirection;
        PGetCalibOffset m_pGetCalibOffset;
        PGetRMOffset m_pGetRMOffset;
        PGetCalibrateDir m_pGetCalibrateDir;
        PSetCalibBackSpeed m_pSetCalibBackSpeed;
        PGetCalibBackSpeed m_pGetCalibBackSpeed;
        PSetRefSpeed m_pSetRefSpeed;
        PGetRefSpeed m_pGetRefSpeed;
        PSetPowerAmplifier m_pSetPowerAmplifier;
        PGetPowerAmplifier m_pGetPowerAmplifier;
        PSetMotorTablePatch m_pSetMotorTablePatch;
        PGetMotorTablePatch m_pGetMotorTablePatch;
        PSetJoystickFilter m_pSetJoystickFilter;
        PGetJoystickFilter m_pGetJoystickFilter;
        PSetStopPolarity m_pSetStopPolarity;
        PGetStopPolarity m_pGetStopPolarity;
        PSetVLevel m_pSetVLevel;
        PGetVLevel m_pGetVLevel;
        PSetStopAccel m_pSetStopAccel;
        PGetStopAccel m_pGetStopAccel;
        PGetVersionStrInfo m_pGetVersionStrInfo;
        PGetVersionStrInfoW m_pGetVersionStrInfoW;
        PGetStatusLimit m_pGetStatusLimit;
        PGetStatusLimitW m_pGetStatusLimitW;
        PGetSecurityErr m_pGetSecurityErr;
        PGetSecurityStatus m_pGetSecurityStatus;
        PGetDelay m_pGetDelay;
        PGetDistance m_pGetDistance;
        PClearPos m_pClearPos;
        PSetDigJoySpeed m_pSetDigJoySpeed;
        PGetDigJoySpeed m_pGetDigJoySpeed;
        PGetJoystickDir m_pGetJoystickDir;
        PGetJoystick m_pGetJoystick;
        PGetJoystickWindow m_pGetJoystickWindow;
        PGetHandWheel m_pGetHandWheel;
        PGetBPZ m_pGetBPZ;
        PGetBPZTrackballFactor m_pGetBPZTrackballFactor;
        PGetBPZTrackballBackLash m_pGetBPZTrackballBackLash;
        PGetBPZJoyspeed m_pGetBPZJoyspeed;
        PGetLimitControl m_pGetLimitControl;
        PSetAutoLimitAfterCalibRM m_pSetAutoLimitAfterCalibRM;
        PGetAutoLimitAfterCalibRM m_pGetAutoLimitAfterCalibRM;
        PGetSwitchPolarity m_pGetSwitchPolarity;
        PGetSwitchActive m_pGetSwitchActive;
        PGetTVRMode m_pGetTVRMode;
        PGetFactorTVR m_pGetFactorTVR;
        PSetTVROutMode m_pSetTVROutMode;
        PGetTVROutMode m_pGetTVROutMode;
        PSetTVROutResolution m_pSetTVROutResolution;
        PGetTVROutResolution m_pGetTVROutResolution;
        PSetTVROutPitch m_pSetTVROutPitch;
        PGetTVROutPitch m_pGetTVROutPitch;
        PSetVelTVRO m_pSetVelTVRO;
        PGetVelTVRO m_pGetVelTVRO;
        PSetAccelTVRO m_pSetAccelTVRO;
        PGetAccelTVRO m_pGetAccelTVRO;
        PSetVelSingleAxisTVRO m_pSetVelSingleAxisTVRO;
        PSetAccelSingleAxisTVRO m_pSetAccelSingleAxisTVRO;
        PSetPosTVRO m_pSetPosTVRO;
        PGetPosTVRO m_pGetPosTVRO;
        PMoveAbsTVRO m_pMoveAbsTVRO;
        PMoveRelTVRO m_pMoveRelTVRO;
        PMoveRelTVROSingleAxis m_pMoveRelTVROSingleAxis;
        PMoveAbsTVROSingleAxis m_pMoveAbsTVROSingleAxis;
        PGetStatusTVRO m_pGetStatusTVRO;
        PGetStatusTVROW m_pGetStatusTVROW;
        PSetTargetWindow m_pSetTargetWindow;
        PGetTargetWindow m_pGetTargetWindow;
        PGetEncoderPeriod m_pGetEncoderPeriod;
        PGetEncoderRefSignal m_pGetEncoderRefSignal;
        PGetEncoderPosition m_pGetEncoderPosition;
        PGetEncoderActive m_pGetEncoderActive;
        PGetController m_pGetController;
        PGetControllerCall m_pGetControllerCall;
        PGetControllerSteps m_pGetControllerSteps;
        PGetControllerFactor m_pGetControllerFactor;
        PGetControllerTWDelay m_pGetControllerTWDelay;
        PGetControllerTimeout m_pGetControllerTimeout;
        PSetCtrFastMoveOn m_pSetCtrFastMoveOn;
        PSetCtrFastMoveOff m_pSetCtrFastMoveOff;
        PGetCtrFastMove m_pGetCtrFastMove;
        PClearCtrFastMoveCounter m_pClearCtrFastMoveCounter;
        PGetCtrFastMoveCounter m_pGetCtrFastMoveCounter;
        PClearEncoder m_pClearEncoder;
        PGetEncoder m_pGetEncoder;
        PGetTrigger m_pGetTrigger;
        PGetTriggerPar m_pGetTriggerPar;
        PSetTrigCount m_pSetTrigCount;
        PGetTrigCount m_pGetTrigCount;
        PSetTVRInPulse m_pSetTVRInPulse;
        PGetSnapshot m_pGetSnapshot;
        PSetSnapshotFilter m_pSetSnapshotFilter;
        PGetSnapshotFilter m_pGetSnapshotFilter;
        PGetSnapshotPar m_pGetSnapshotPar;
        PGetLimit m_pGetLimit;
        PJoyChangeAxis m_pJoyChangeAxis;
        PGetJoyChangeAxis m_pGetJoyChangeAxis;
        PSetDigJoyOff m_pSetDigJoyOff;
        PSetInputTrigMove m_pSetInputTrigMove;
        PGetInputTrigMove m_pGetInputTrigMove;
        PSetLimitControlMode m_pSetLimitControlMode;
        PGetLimitControlMode m_pGetLimitControlMode;
        PInitialize m_pInitialize;
        PInitializeW m_pInitializeW;
        PSetAccelJerk m_pSetAccelJerk;
        PSetDecelJerk m_pSetDecelJerk;
        PSetCalibRMJerk m_pSetCalibRMJerk;
        PSetJoyVel m_pSetJoyVel;
        PGetJoyVel m_pGetJoyVel;
        PSetDeceleration m_pSetDeceleration;
        PGetDeceleration m_pGetDeceleration;
        PSetDecelSingleAxis m_pSetDecelSingleAxis;
        PConfigMaxAxes m_pConfigMaxAxes;
        PSetJoystickAxes m_pSetJoystickAxes;
        PGetJoystickAxes m_pGetJoystickAxes;
        PSetJoyVelSkal m_pSetJoyVelSkal;
        PGetJoyVelSkal m_pGetJoyVelSkal;
        PSetMaxUserCurrent m_pSetMaxUserCurrent;
        PGetMaxUserCurrent m_pGetMaxUserCurrent;
        PSetStopDecel m_pSetStopDecel;
        PGetStopDecel m_pGetStopDecel;
        PSetMotorMaxVel m_pSetMotorMaxVel;
        PGetMotorMaxVel m_pGetMotorMaxVel;
        PSetMotorStandForce m_pSetMotorStandForce;
        PGetMotorStandForce m_pGetMotorStandForce;
        PSetMotorStandMoment m_pSetMotorStandMoment;
        PGetMotorStandMoment m_pGetMotorStandMoment;
        PSetMotorFieldDir m_pSetMotorFieldDir;
        PGetMotorFieldDir m_pGetMotorFieldDir;
        PSetMotorType m_pSetMotorType;
        PGetMotorType m_pGetMotorType;
        PSetOsziCallBackFct m_pSetOsziCallBackFct;
        PTranslateErrMsg m_pTranslateErrMsg;
        PSetCalibRMAccel m_pSetCalibRMAccel;
        PGetCalibRMAccel m_pGetCalibRMAccel;
        PGetCalibRMJerk m_pGetCalibRMJerk;
        PSetCalibRMVel m_pSetCalibRMVel;
        PGetCalibRMVel m_pGetCalibRMVel;
        PSetCalibRMBackSpeed m_pSetCalibRMBackSpeed;
        PGetCalibRMBackSpeed m_pGetCalibRMBackSpeed;
        PGetAccelJerk m_pGetAccelJerk;
        PGetDecelJerk m_pGetDecelJerk;
        PSetGearDenominator m_pSetGearDenominator;
        PGetGearDenominator m_pGetGearDenominator;
        PSetGearNumerator m_pSetGearNumerator;
        PGetGearNumerator m_pGetGearNumerator;
        PSetStopDecelJerk m_pSetStopDecelJerk;
        PGetStopDecelJerk m_pGetStopDecelJerk;
        PSetSwChange m_pSetSwChange;
        PGetSwChange m_pGetSwChange;
        PCreateLSID m_pCreateLSID;
        PFreeLSID m_pFreeLSID;

public:
			CLStep4X();
			~CLStep4X();

	int		GetDLLLoadResult() {return m_DLLResultat;}; // Funktion, ob Laden der DLL erfolgreich war.
	// sollte Wert 0 zurückgeben

	// Funktionen der Dll
        int Connect ();
        int ConnectSimple (int lAnInterfaceType, char *pcAComName, int lABaudRate, BOOL bAShowProt);
        int ConnectSimpleW (int lAnInterfaceType, TCHAR *pcAComName, int lABaudRate, BOOL bAShowProt);
        int ConnectEx (TLS_ControlInitPar *pAControlInitPar);
        int ConnectExW (TLS_ControlInitParW *pAControlInitPar);
        int Disconnect ();
        int LoadConfig (char *pcFileName);
        int LoadConfigW (TCHAR *pcFileName);
        int SaveConfig (char *pcFileName);
        int SaveConfigW (TCHAR *pcFileName);
        int MoveAbs (double dX, double dY, double dZ, double dA, BOOL bWait);
        int MoveRel (double dX, double dY, double dZ, double dA, BOOL bWait);
        int Calibrate ();
        int RMeasure ();
        int SetPitch (double dX, double dY, double dZ, double dA);
        int SetPos (double dX, double dY, double dZ, double dA);
        int SetActiveAxes (int lFlags);
        int SetVel (double dX, double dY, double dZ, double dA);
        int SetAccel (double dX, double dY, double dZ, double dA);
        int SetReduction (double dX, double dY, double dZ, double dA);
        int SetDelay (int lDelay);
        int SetSwitchPolarity (int lXP, int lYP, int lZP, int lAP);
        int SetSwitchActive (int lXA, int lYA, int lZA, int lAA);
        int SetJoystickOn (BOOL bPositionCount, BOOL bEncoder);
        int SetJoystickOff ();
        int SoftwareReset ();
        int SetDigitalOutput (int lIndex, BOOL bValue);
        int GetDigitalInputs (int *plValue);
        int SetAnalogOutput (int lIndex, int lValue);
        int GetAnalogInput (int lIndex, int *plValue);
        int SetLimit (int lAxis, double dMinRange, double dMaxRange);
        int SetLimitControl (int lAxis, BOOL bActive);
        int GetPos (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetStatus (char *pcStat, int lMaxLen);
        int GetStatusW (TCHAR *pcStat, int lMaxLen);
        int GetEncoderMask (int *plFlags);
        int StopAxes ();
        int SetAbortFlag ();
        int MoveRelSingleAxis (int lAxis, double dValue, BOOL bWait);
        int MoveAbsSingleAxis (int lAxis, double dValue, BOOL bWait);
        int MoveSequence (int lnMode, BOOL bWait);
        int SetControlPars ();
        int SetMotorCurrent (double dX, double dY, double dZ, double dA);
        int SetVelSingleAxis (int lAxis, double dVel);
        int SetAccelSingleAxis (int lAxis, double dAccel);
        int CalibrateEx (int lFlags);
        int RMeasureEx (int lFlags);
        int SetShowProt (BOOL bShowProt);
        int GetAnalogInputs2 (int *plPT100, int *plMV, int *plV24);
        int SendString (char *pcStr, char *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
        int SendStringW (TCHAR *pcStr, TCHAR *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
        int SetSpeedPoti (BOOL bSpeedPoti);
        int SetTVRMode (int lXT, int lYT, int lZT, int lAT);
        int SetAutoStatus (int lValue);
        int GetStatusAxis (char *pcStatusAxisStr, int lMaxLen);
        int GetStatusAxisW (TCHAR *pcStatusAxisStr, int lMaxLen);
        int SetDigIO_Off (int lIndex);
        int SetDigIO_Polarity (int lIndex, BOOL bHigh);
        int SetDigIO_EmergencyStop (int lIndex);
        int SetDigIO_Distance (int lIndex, BOOL bFkt, double dDist, int lAxis);
        int SetDimensions (int lXD, int lYD, int lZD, int lAD);
        int MoveRelShort ();
        int SetEncoderPeriod (double dX, double dY, double dZ, double dA);
        int SetJoystickDir (int lXD, int lYD, int lZD, int lAD);
        int SetEncoderMask (int lValue);
        int SetGear (double dX, double dY, double dZ, double dA);
        int SetHandWheelOn (BOOL bPositionCount, BOOL bEncoder);
        int SetHandWheelOff ();
        int SetFactorTVR (double dX, double dY, double dZ, double dA);
        int SetController (int lXC, int lYC, int lZC, int lAC);
        int SetControllerCall (int lCtrCall);
        int SetControllerSteps (double dX, double dY, double dZ, double dA);
        int SetControllerFactor (double dX, double dY, double dZ, double dA);
        int SetControllerTWDelay (int lCtrTWDelay);
        int SetEncoderRefSignal (int lXR, int lYR, int lZR, int lAR);
        int SetEncoderPosition (BOOL bValue);
        int GetVersionStr (char *pcVers, int lMaxLen);
        int GetVersionStrW (TCHAR *pcVers, int lMaxLen);
        int GetError (int *plErrorCode);
        int GetPosSingleAxis (int lAxis, double *pdPos);
        int SetDistance (double dX, double dY, double dZ, double dA);
        int GetPosEx (double *pdX, double *pdY, double *pdZ, double *pdR, BOOL bEncoder);
        int SetShowCmdList (BOOL bShowCmdList);
        int SetWriteLogText (BOOL bAWriteLogText);
        int SetControllerTimeout (int lACtrTimeout);
        int SetEncoderActive (int lFlags);
        int GetSnapshotCount (int *plSnsCount);
        int GetSnapshotPos (double *pdX, double *pdY, double *pdZ, double *pdA);
        int SetCorrTblOff ();
        int SetCorrTblOn (char *pcAFileName);
        int SetCorrTblOnW (TCHAR *pcAFileName);
        int SetFactorMode (BOOL bAFactorMode, double dX, double dY, double dZ, double dA);
        int SetSnapshot (BOOL bASnapshot);
        int SetSnapshotPar (BOOL bHigh, BOOL bAutoMode);
        int SetTrigger (BOOL bATrigger);
        int SetTriggerPar (int lAxis, int lMode, int lSignal, double dDistance);
        int SetLanguage (char *pcPLN);
        int SetLanguageW (TCHAR *pcPLN);
        int GetSwitches (int *plFlags);
        int GetSerialNr (char *pcSerialNr, int lMaxLen);
        int GetSerialNrW (TCHAR *pcSerialNr, int lMaxLen);
        int SetCalibOffset (double dX, double dY, double dZ, double dR);
        int SetRMOffset (double dX, double dY, double dZ, double dR);
        int GetSnapshotPosArray (int lIndex, double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetAxisDirection (int lXD, int lYD, int lZD, int lAD);
        int SetCalibrateDir (int lXD, int lYD, int lZD, int lAD);
        int LStepSave ();
        int SetBPZ (int lAValue);
        int SetBPZTrackballFactor (double dAValue);
        int SetBPZTrackballBackLash (double dX, double dY, double dZ, double dR);
        int SetBPZJoyspeed (int lAPar, double dAValue);
        int SetJoystickWindow (int lAValue);
        int SetCurrentDelay (int lX, int lY, int lZ, int lR);
        int MoveEx (double dX, double dY, double dZ, double dR, BOOL bRelative, BOOL bWait, int lAxisCount);
        int WaitForAxisStop (int lAFlags, int lATimeoutValue, BOOL *pbATimeout);
        int SendStringPosCmd (char *pcStr, char *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
        int SendStringPosCmdW (TCHAR *pcStr, TCHAR *pcRet, int lMaxLen, BOOL bReadLine, int lTimeOut);
        int SetDigitalOutputs (int lValue);
        int SetWriteLogTextFN (BOOL bAWriteLogText, char *pcALogFN);
        int SetWriteLogTextFNW (BOOL bAWriteLogText, TCHAR *pcALogFN);
        int SetDigitalOutputsE (int lValue);
        int GetDigitalInputsE (int *plValue);
        int EnableCommandRetry (BOOL bAValue);
        int SetXYAxisComp (int lValue);
        int GetVersionStrDet (char *pcVersDet, int lMaxLen);
        int GetVersionStrDetW (TCHAR *pcVersDet, int lMaxLen);
        int GetAPIVersion (char *pcAPIVer, int lMaxLen);
        int GetAPIVersionW (TCHAR *pcAPIVer, int lMaxLen);
        int SetCommandTimeout (int lAtoRead, int lAtoMove, int lAtoCalibrate);
        int SetExtValue (int lAName, int lAValue);
        int FlushBuffer (int lAValue);
        int SetProcessMessagesProc (void* pProc);
        int GetEEPRomValue (byte Offset, byte *pValue);
        int SetEEPRomValue (byte Offset, byte Value);
        int GetXYAxisComp (int *plValue);
        int GetDimensions (int *plXD, int *plYD, int *plZD, int *plAD);
        int GetPitch (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetGear (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetVel (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetAccel (double *pdX, double *pdY, double *pdZ, double *pdA);
        int SetVelFac (double dX, double dY, double dZ, double dR);
        int SetVelFacSingleAxis (int lAxis, double dX, double dY, double dZ, double dR);
        int GetVelFac (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetSpeedPoti (BOOL *pbSpePoti);
        int GetMotorCurrent (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetReduction (double *pdX, double *pdY, double *pdZ, double *pdA);
        int GetCurrentDelay (int *plX, int *plY, int *plZ, int *plR);
        int SetOutFuncLev (double dX, double dY, double dZ, double dR);
        int GetOutFuncLev (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetActiveAxes (int *plFlags);
        int GetAxisDirection (int *plXD, int *plYD, int *plZD, int *plAD);
        int GetCalibOffset (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetRMOffset (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetCalibrateDir (int *plXD, int *plYD, int *plZD, int *plAD);
        int SetCalibBackSpeed (int lSpeed);
        int GetCalibBackSpeed (int *plSpeed);
        int SetRefSpeed (int lSpeed);
        int GetRefSpeed (int *plSpeed);
        int SetPowerAmplifier (BOOL bAmplifier);
        int GetPowerAmplifier (BOOL *pbAmplifier);
        int SetMotorTablePatch (BOOL bActive);
        int GetMotorTablePatch (BOOL *pbActive);
        int SetJoystickFilter (BOOL bActive);
        int GetJoystickFilter (BOOL *pbActive);
        int SetStopPolarity (BOOL bHighActiv);
        int GetStopPolarity (BOOL *pbHighActiv);
        int SetVLevel (int lVRegion, double dDownLevel, double dUppLevel);
        int GetVLevel (int lVRegion, double *pdDownLevel, double *pdUppLevel);
        int SetStopAccel (double dXD, double dYD, double dZD, double dAD);
        int GetStopAccel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int GetVersionStrInfo (char *pcVersInfo, int lMaxLen);
        int GetVersionStrInfoW (TCHAR *pcVersInfo, int lMaxLen);
        int GetStatusLimit (char *pcLimit, int lMaxLen);
        int GetStatusLimitW (TCHAR *pcLimit, int lMaxLen);
        int GetSecurityErr (DWORD *pdwValue);
        int GetSecurityStatus (DWORD *pdwValue);
        int GetDelay (int *plDelay);
        int GetDistance (double *pdX, double *pdY, double *pdZ, double *pdR);
        int ClearPos (int lFlags);
        int SetDigJoySpeed (double dX, double dY, double dZ, double dR);
        int GetDigJoySpeed (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetJoystickDir (int *plXD, int *plYD, int *plZD, int *plRD);
        int GetJoystick (BOOL *pbJoystickOn, BOOL *pbManual, BOOL *pbPositionCount, BOOL *pbEncoder);
        int GetJoystickWindow (int *plAValue);
        int GetHandWheel (BOOL *pbHandWheelOn, BOOL *pbPositionCount, BOOL *pbEncoder);
        int GetBPZ (int *plAValue);
        int GetBPZTrackballFactor (double *pdAValue);
        int GetBPZTrackballBackLash (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetBPZJoyspeed (int lAPar, double *pdAValue);
        int GetLimitControl (int lAxis, BOOL *pbActive);
        int SetAutoLimitAfterCalibRM (int lFlags);
        int GetAutoLimitAfterCalibRM (int *plFlags);
        int GetSwitchPolarity (int *plXP, int *plYP, int *plZP, int *plRP);
        int GetSwitchActive (int *plXA, int *plYA, int *plZA, int *plRA);
        int GetTVRMode (int *plXT, int *plYT, int *plZT, int *plRT);
        int GetFactorTVR (double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetTVROutMode (int lXT, int lYT, int lZT, int lRT);
        int GetTVROutMode (int *plXT, int *plYT, int *plZT, int *plRT);
        int SetTVROutResolution (int lX, int lY, int lZ, int lR);
        int GetTVROutResolution (int *plX, int *plY, int *plZ, int *plR);
        int SetTVROutPitch (double dX, double dY, double dZ, double dR);
        int GetTVROutPitch (double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetVelTVRO (double dX, double dY, double dZ, double dR);
        int GetVelTVRO (double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetAccelTVRO (double dX, double dY, double dZ, double dR);
        int GetAccelTVRO (double *pdX, double *pdY, double *pdZ, double *pdR);
        int SetVelSingleAxisTVRO (int lAxis, double dVel);
        int SetAccelSingleAxisTVRO (int lAxis, double dAccel);
        int SetPosTVRO (double dX, double dY, double dZ, double dR);
        int GetPosTVRO (double *pdX, double *pdY, double *pdZ, double *pdR);
        int MoveAbsTVRO (double dX, double dY, double dZ, double dR, BOOL bWait);
        int MoveRelTVRO (double dX, double dY, double dZ, double dR, BOOL bWait);
        int MoveRelTVROSingleAxis (int lAxis, double dValue, BOOL bWait);
        int MoveAbsTVROSingleAxis (int lAxis, double dValue, BOOL bWait);
        int GetStatusTVRO (char *pcStat, int lMaxLen);
        int GetStatusTVROW (TCHAR *pcStat, int lMaxLen);
        int SetTargetWindow (double dX, double dY, double dZ, double dR);
        int GetTargetWindow (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetEncoderPeriod (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetEncoderRefSignal (int *plXR, int *plYR, int *plZR, int *plRR);
        int GetEncoderPosition (BOOL *pbValue);
        int GetEncoderActive (int *plFlags);
        int GetController (int *plXC, int *plYC, int *plZC, int *plRC);
        int GetControllerCall (int *plCtrCall);
        int GetControllerSteps (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetControllerFactor (double *pdX, double *pdY, double *pdZ, double *pdR);
        int GetControllerTWDelay (int *plCtrTWDelay);
        int GetControllerTimeout (int *plACtrTimeout);
        int SetCtrFastMoveOn ();
        int SetCtrFastMoveOff ();
        int GetCtrFastMove (BOOL *pbActive);
        int ClearCtrFastMoveCounter ();
        int GetCtrFastMoveCounter (int *plXC, int *plYC, int *plZC, int *plRC);
        int ClearEncoder (int lAxis);
        int GetEncoder (double *pdXP, double *pdYP, double *pdZP, double *pdRP);
        int GetTrigger (BOOL *pbATrigger);
        int GetTriggerPar (int *plAxis, int *plMode, int *plSignal, double *pdDistance);
        int SetTrigCount (int lValue);
        int GetTrigCount (int *plValue);
        int SetTVRInPulse (int lAxis, BOOL bDirection);
        int GetSnapshot (BOOL *pbASnapshot);
        int SetSnapshotFilter (int lTime);
        int GetSnapshotFilter (int *plTime);
        int GetSnapshotPar (BOOL *pbHigh, BOOL *pbAutoMode);
        int GetLimit (int lAxis, double *pdMinRange, double *pdMaxRange);
        int JoyChangeAxis (BOOL bValue);
        int GetJoyChangeAxis (BOOL *pbValue);
        int SetDigJoyOff ();
        int SetInputTrigMove (int lMode, BOOL bWait);
        int GetInputTrigMove (int *plMode);
        int SetLimitControlMode (int lMode);
        int GetLimitControlMode (int *plMode);
        int Initialize (char *pcWorkpath);
        int InitializeW (TCHAR *pcWorkpath);
        int SetAccelJerk (double dXD, double dYD, double dZD, double dAD);
        int SetDecelJerk (double dXD, double dYD, double dZD, double dAD);
        int SetCalibRMJerk (double dXD, double dYD, double dZD, double dAD);
        int SetJoyVel (double dXD, double dYD, double dZD, double dAD);
        int GetJoyVel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetDeceleration (double dXD, double dYD, double dZD, double dAD);
        int GetDeceleration (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetDecelSingleAxis (int lAxis, double dValue);
        int ConfigMaxAxes (int lnAxes);
        int SetJoystickAxes (int lFlags);
        int GetJoystickAxes (int *plFlags);
        int SetJoyVelSkal (int lX, int lY, int lZ, int lR);
        int GetJoyVelSkal (int *plX, int *plY, int *plZ, int *plR);
        int SetMaxUserCurrent (double dXD, double dYD, double dZD, double dAD);
        int GetMaxUserCurrent (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetStopDecel (double dXD, double dYD, double dZD, double dAD);
        int GetStopDecel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetMotorMaxVel (double dXD, double dYD, double dZD, double dAD);
        int GetMotorMaxVel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetMotorStandForce (double dXD, double dYD, double dZD, double dAD);
        int GetMotorStandForce (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetMotorStandMoment (double dXD, double dYD, double dZD, double dAD);
        int GetMotorStandMoment (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetMotorFieldDir (int lX, int lY, int lZ, int lA);
        int GetMotorFieldDir (int *plX, int *plY, int *plZ, int *plA);
        int SetMotorType (int lX, int lY, int lZ, int lA);
        int GetMotorType (int *plX, int *plY, int *plZ, int *plA);
        int SetOsziCallBackFct (void* pFct);
        int TranslateErrMsg (TCHAR *pcMsgIn, TCHAR *pcMsgOut, int lMaxLen);
        int SetCalibRMAccel (double dXD, double dYD, double dZD, double dAD);
        int GetCalibRMAccel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int GetCalibRMJerk (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetCalibRMVel (double dXD, double dYD, double dZD, double dAD);
        int GetCalibRMVel (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetCalibRMBackSpeed (double dXD, double dYD, double dZD, double dAD);
        int GetCalibRMBackSpeed (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int GetAccelJerk (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int GetDecelJerk (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetGearDenominator (int lX, int lY, int lZ, int lR);
        int GetGearDenominator (int *plX, int *plY, int *plZ, int *plR);
        int SetGearNumerator (int lX, int lY, int lZ, int lR);
        int GetGearNumerator (int *plX, int *plY, int *plZ, int *plR);
        int SetStopDecelJerk (double dXD, double dYD, double dZD, double dAD);
        int GetStopDecelJerk (double *pdXD, double *pdYD, double *pdZD, double *pdAD);
        int SetSwChange (int lFlags);
        int GetSwChange (int *plFlags);
    }; */

#endif // __CLStep4X__
